services:
  web:
    build:
      context: ..
      dockerfile: local/Dockerfile.local
    container_name: ${WEB_CONTAINER_NAME}
    ports:
      - "${APP_PORT}:8501"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - PYTHONUNBUFFERED=1
    volumes:
      - ../model/saved_models:/app/model/saved_models:ro
    depends_on:
      - db

  db:
    image: postgres:${DB_VERSION}
    container_name: ${DB_CONTAINER_NAME}
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_INITDB_ARGS=--data-checksums
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - mnist-digit-recognizer-db-volume:/var/lib/postgresql/data
      - ../database/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          memory: 256M

volumes:
  mnist-digit-recognizer-db-volume: 