# LOCAL ENVIRONMENT OVERRIDES
# This file contains overrides specific to local development

services:
  # WEB APPLICATION SERVICE
  web:
    build:
      context: ..
      dockerfile: local/Dockerfile.local
    environment:
      - MODEL_PATH=${MODEL_PATH}
    volumes:
      - ../model/saved_models:/app/model/saved_models:ro