# MNIST DIGIT RECOGNIZER APPLICATION
# Docker Compose configuration file

version: '3'

services:
  # WEB APPLICATION SERVICE
  web:
    container_name: ${WEB_CONTAINER_NAME}
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${APP_PORT}:${APP_PORT}"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - MODEL_PATH=${MODEL_PATH}
    volumes:
      - ./model/trained_model.pth:/model/trained_model.pth:ro
    depends_on:
      - db
    restart: unless-stopped

  # DATABASE SERVICE
  db:
    container_name: ${DB_CONTAINER_NAME}
    image: postgres:${DB_VERSION}
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_INITDB_ARGS=${POSTGRES_INITDB_ARGS}
      - PGDATA=${PGDATA}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - ./init.sql:/init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

# VOLUME CONFIGURATION
volumes:
  mnist-digit-recogniser-db-volume:
    name: ${DB_VOLUME_NAME}