version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
    restart: always
    ports:
      - "8501:8501"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=mnist_db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    volumes:
      - ./saved_models:/app/saved_models
    networks:
      - mnist-network

  db:
    image: postgres:13
    restart: always
    environment:
      - POSTGRES_DB=mnist_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - mnist-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  mnist-network:
    driver: bridge

volumes:
  postgres_data: 