services:
  web:
    build:
      dockerfile: server/deployment/Dockerfile
    container_name: ${WEB_CONTAINER_NAME}
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          memory: 512M

  db:
    container_name: ${DB_CONTAINER_NAME}
    restart: unless-stopped
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          memory: 256M

volumes:
  db-data:
    name: ${DB_VOLUME_NAME} 