# MNIST Digit Recognizer Application
# Docker Compose configuration file

services:
  # Web Application Service
  web:
    build:
      context: .
    ports:
      - "${APP_PORT}:8501"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - PYTHONUNBUFFERED=1
    volumes:
      - ./model/saved_models:/app/model/saved_models:ro
    depends_on:
      - db

  # Database Service
  db:
    image: postgres:${DB_VERSION}
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      # Prevent data loss during container recreation
      - POSTGRES_INITDB_ARGS=--data-checksums
      # Add the following environment variable to make init scripts run on each restart
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

# Network Configuration
networks:
  mnist-network:
    driver: bridge

# Volume Configuration
volumes:
  db-data:
  mnist-digit-recognizer-db-volume:
    driver: local 