# MNIST DIGIT RECOGNIZER APPLICATION
# Base Docker Compose configuration file

services:
  # WEB APPLICATION SERVICE
  web:
    container_name: ${WEB_CONTAINER_NAME}
    build:
      context: .
    ports:
      - "${APP_PORT}:8501"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - PYTHONUNBUFFERED=1
    volumes:
      - ./model/saved_models:/app/model/saved_models:ro
    depends_on:
      - db

  # DATABASE SERVICE
  db:
    container_name: ${DB_CONTAINER_NAME}
    image: postgres:${DB_VERSION}
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_INITDB_ARGS=${POSTGRES_INITDB_ARGS}
      - PGDATA=${PGDATA}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - mnist-digit-recogniser-db-volume:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

# VOLUME CONFIGURATION
volumes:
  mnist-digit-recogniser-db-volume:
    name: ${DB_VOLUME_NAME}