# MNIST Digit Recognizer Application
# Docker Compose configuration file

services:
  # Web Application Service
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
    restart: unless-stopped
    container_name: mnist-digit-recognizer-web-1
    ports:
      - "8501:8501"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=mnist_db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - PYTHONUNBUFFERED=1
    volumes:
      - ./model/saved_models:/app/model/saved_models:ro
    networks:
      - mnist-network
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          memory: 512M

  # Database Service
  db:
    image: postgres:13
    restart: unless-stopped
    container_name: mnist-digit-recognizer-db-1
    environment:
      - POSTGRES_DB=mnist_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "5432:5432"
    networks:
      - mnist-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          memory: 256M

# Network Configuration
networks:
  mnist-network:
    driver: bridge

# Volume Configuration
volumes:
  postgres_data:
    driver: local 