# REMOTE ENVIRONMENT OVERRIDES
# This file contains overrides specific to server deployment

services:
  # WEB APPLICATION SERVICE
  web:
    build:
      dockerfile: ${DOCKERFILE_PATH}
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          memory: 512M

  # DATABASE SERVICE
  db:
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          memory: 256M