# REMOTE ENVIRONMENT OVERRIDES
# This file contains overrides specific to server deployment

services:
  # WEB APPLICATION SERVICE
  web:
    build:
      context: ..
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - STREAMLIT_SERVER_ENABLE_CORS=false
      - IS_DEVELOPMENT=false
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          memory: 512M

  # DATABASE SERVICE
  db:
    restart: unless-stopped
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          memory: 256M